#!/usr/bin/env bash
set -euo pipefail

# Opens a draft PR in each repo (game-datacards, gdc-premium) that the agent
# changed, cross-links them to the originating issue, and comments on the issue
# with the result. Pushes a branch named ai/issue-<n> in each changed repo so the
# existing scripts/build-premium.sh branch-matching links the two at build time.
#
# Required env:
#   GITHUB_WORKSPACE  parent dir containing game-datacards/ and gdc-premium/
#   GH_TOKEN          PAT with contents + pull-requests + issues write on both repos
#   ISSUE_NUMBER      issue number in game-datacards
#   ISSUE_TITLE       issue title
#   GAME_REPO         owner/repo, e.g. ronplanken/game-datacards
#   PREMIUM_REPO      owner/repo, e.g. ronplanken/gdc-premium
#   CHECKS            human-readable lint/test status line
# Optional:
#   PREMIUM_BASE      base branch for the premium PR (default: main)
#   BOT_NAME, BOT_EMAIL

BRANCH="ai/issue-${ISSUE_NUMBER}"
PREMIUM_BASE="${PREMIUM_BASE:-main}"
BOT_NAME="${BOT_NAME:-gdc-issue-bot}"
BOT_EMAIL="${BOT_EMAIL:-issue-bot@users.noreply.github.com}"

declare -a CREATED=()

# Commit any working-tree changes in a repo and open a draft PR. Returns silently
# (no PR) when the repo has no changes.
push_and_pr() {
  local dir="$1" repo="$2" base="$3" body="$4"
  local path="${GITHUB_WORKSPACE}/${dir}"

  git -C "$path" add -A
  if git -C "$path" diff --cached --quiet; then
    echo "No changes in ${dir}; skipping PR."
    return 0
  fi

  git -C "$path" -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" \
    commit -m "Implement #${ISSUE_NUMBER}: ${ISSUE_TITLE}"
  git -C "$path" push -u origin "$BRANCH" --force-with-lease

  local url
  if url="$(gh pr create \
      --repo "$repo" --draft --base "$base" --head "$BRANCH" \
      --title "AI draft: ${ISSUE_TITLE} (#${ISSUE_NUMBER})" \
      --body "$body" --label ai-generated)"; then
    echo "Created PR: $url"
    CREATED+=("${repo}: ${url}")
  else
    echo "Failed to open PR in ${repo} (it may already exist for ${BRANCH})." >&2
  fi
}

GAME_BODY="Automated draft for ${GAME_REPO}#${ISSUE_NUMBER}.

Refs #${ISSUE_NUMBER}

Generated by the issue-to-pr pipeline. This is a draft and requires human review
before merge. A matching branch \`${BRANCH}\` may also exist in ${PREMIUM_REPO}
and is linked at premium-build time.

Checks: ${CHECKS}"

PREMIUM_BODY="Automated draft accompanying ${GAME_REPO}#${ISSUE_NUMBER}.

Implements the premium-package side of that feature. Pairs with branch
\`${BRANCH}\` in ${GAME_REPO} (linked via scripts/build-premium.sh branch
matching). Draft; requires human review before merge.

Checks: ${CHECKS}"

push_and_pr "game-datacards" "$GAME_REPO" "main" "$GAME_BODY"
push_and_pr "gdc-premium" "$PREMIUM_REPO" "$PREMIUM_BASE" "$PREMIUM_BODY"

# Report back on the issue.
if [ "${#CREATED[@]}" -eq 0 ]; then
  COMMENT="The issue-to-pr pipeline ran but produced no code changes. The request
may be too ambiguous, too large, or out of scope for an automated attempt. To
retry after clarifying the issue, remove the \`ai-attempted\` label and re-add
\`ai-build\`."
else
  printf -v JOINED -- "- %s\n" "${CREATED[@]}"
  COMMENT="Draft PR(s) opened by the issue-to-pr pipeline:

${JOINED}
Checks: ${CHECKS}

These are drafts and require human review. CI and the Claude review run
automatically on each PR."
fi

gh issue comment "$ISSUE_NUMBER" --repo "$GAME_REPO" --body "$COMMENT"
