#!/usr/bin/env bash
set -euo pipefail

# Opens a draft PR in each repo (game-datacards, gdc-premium) that the agent
# changed, cross-links them to the originating issue, and comments on the issue
# with the result. Pushes the branch named in $BRANCH (e.g.
# feature/<n>-<slug> or bug/<n>-<slug>, set by the workflow's gate job) in each
# changed repo so the existing scripts/build-premium.sh branch-matching links the
# two at build time. Both repos must use the same branch name.
#
# The PR body is assembled from the agent's own plain-language summary
# (pr-summary.md, written outside both repos so it is never committed), the
# actual git diffstat of the change, the issue link, the lint/test status, and
# the OpenCode token/cost usage for the run.
#
# Required env:
#   GITHUB_WORKSPACE  parent dir containing game-datacards/ and gdc-premium/
#   GH_TOKEN          PAT with contents + pull-requests + issues write on both repos
#   BRANCH            working branch name, same in both repos
#   ISSUE_NUMBER      issue number in game-datacards
#   ISSUE_TITLE       issue title
#   GAME_REPO         owner/repo, e.g. ronplanken/game-datacards
#   PREMIUM_REPO      owner/repo, e.g. ronplanken/gdc-premium
#   CHECKS            human-readable lint/test status line
# Optional:
#   SUMMARY_FILE      path to the agent's PR summary (default: $GITHUB_WORKSPACE/pr-summary.md)
#   USAGE_FILE        path to the OpenCode usage stats text
#   PREMIUM_BASE      base branch for the premium PR (default: main)
#   BOT_NAME, BOT_EMAIL

BRANCH="${BRANCH:?BRANCH must be set by the workflow}"
PREMIUM_BASE="${PREMIUM_BASE:-main}"
BOT_NAME="${BOT_NAME:-gdc-issue-bot}"
BOT_EMAIL="${BOT_EMAIL:-issue-bot@users.noreply.github.com}"
SUMMARY_FILE="${SUMMARY_FILE:-${GITHUB_WORKSPACE}/pr-summary.md}"

# Read the agent summary and usage stats if present; both degrade gracefully.
SUMMARY=""
if [ -s "$SUMMARY_FILE" ]; then
  SUMMARY="$(cat "$SUMMARY_FILE")"
fi
USAGE=""
if [ -n "${USAGE_FILE:-}" ] && [ -s "$USAGE_FILE" ]; then
  USAGE="$(cat "$USAGE_FILE")"
fi

declare -a CREATED=()

# Build a PR body. $1 repo, $2 role (game|premium), $3 diffstat text.
# Variable content is always passed as a %s argument so stray % or backticks in
# a summary/diffstat can never be read as a printf format.
build_body() {
  local repo="$1" role="$2" diffstat="$3" link summary

  # Same-repo PRs use "Closes #N" so merging the PR closes the issue. The premium
  # PR lives in another repo, where the keyword would not auto-close, so it only
  # references the issue.
  if [ "$repo" = "$GAME_REPO" ]; then
    link="Closes #${ISSUE_NUMBER}"
  else
    link="Implements ${GAME_REPO}#${ISSUE_NUMBER}"
  fi

  if [ -n "$SUMMARY" ]; then
    summary="$SUMMARY"
  else
    summary="_The agent left no summary. See the changed files below._"
  fi

  printf '%s\n\n' "$link"
  if [ "$role" = "premium" ]; then
    printf 'Premium-package side of this change. Pairs with branch `%s` in %s (linked via scripts/build-premium.sh branch matching).\n\n' \
      "$BRANCH" "$GAME_REPO"
  fi
  printf '## What changed and why\n\n%s\n\n' "$summary"
  printf '## Files changed\n\n```\n%s\n```\n\n' "$diffstat"
  printf '## Checks\n\n%s\n\n' "${CHECKS:-not reported}"
  if [ -n "$USAGE" ]; then
    printf '## OpenCode usage\n\n<details><summary>Token and cost totals for this run</summary>\n\n```\n%s\n```\n\n</details>\n\n' "$USAGE"
  fi
  printf -- '---\nDraft generated by the issue-to-pr pipeline. Requires human review before merge. CI and the Claude review run automatically on each PR.\n'
}

# Commit any working-tree changes in a repo and open a draft PR. Returns silently
# (no PR) when the repo has no changes.
push_and_pr() {
  local dir="$1" repo="$2" base="$3" role="$4"
  local path="${GITHUB_WORKSPACE}/${dir}"

  git -C "$path" add -A
  if git -C "$path" diff --cached --quiet; then
    echo "No changes in ${dir}; skipping PR."
    return 0
  fi

  # Capture the diffstat of exactly what we are about to commit.
  local diffstat
  diffstat="$(git -C "$path" diff --cached --stat)"

  git -C "$path" -c user.name="$BOT_NAME" -c user.email="$BOT_EMAIL" \
    commit -m "Implement #${ISSUE_NUMBER}: ${ISSUE_TITLE}"
  git -C "$path" push -u origin "$BRANCH" --force-with-lease

  local body url
  body="$(build_body "$repo" "$role" "$diffstat")"
  if url="$(gh pr create \
      --repo "$repo" --draft --base "$base" --head "$BRANCH" \
      --title "AI draft: ${ISSUE_TITLE} (#${ISSUE_NUMBER})" \
      --body "$body" --label ai-generated)"; then
    echo "Created PR: $url"
    CREATED+=("${repo}: ${url}")
  else
    echo "Failed to open PR in ${repo} (it may already exist for ${BRANCH})." >&2
  fi
}

push_and_pr "game-datacards" "$GAME_REPO" "main" "game"
push_and_pr "gdc-premium" "$PREMIUM_REPO" "$PREMIUM_BASE" "premium"

# Report back on the issue.
if [ "${#CREATED[@]}" -eq 0 ]; then
  COMMENT="The issue-to-pr pipeline ran but produced no code changes. The request
may be too ambiguous, too large, or out of scope for an automated attempt. To
retry after clarifying the issue, remove the \`ai-attempted\` label and re-add
\`ai-build\`."
else
  printf -v JOINED -- "- %s\n" "${CREATED[@]}"
  COMMENT="$(printf 'Draft PR(s) opened by the issue-to-pr pipeline:\n\n%s' "$JOINED")"
  if [ -n "$SUMMARY" ]; then
    COMMENT="$(printf '%s\n**What changed:**\n\n%s\n' "$COMMENT" "$SUMMARY")"
  fi
  COMMENT="$(printf '%s\nChecks: %s\n' "$COMMENT" "${CHECKS:-not reported}")"
  if [ -n "$USAGE" ]; then
    COMMENT="$(printf '%s\n<details><summary>OpenCode usage</summary>\n\n```\n%s\n```\n\n</details>\n' "$COMMENT" "$USAGE")"
  fi
  COMMENT="$(printf '%s\nThese are drafts and require human review.\n' "$COMMENT")"
fi

gh issue comment "$ISSUE_NUMBER" --repo "$GAME_REPO" --body "$COMMENT"
